### ISSUE TITLE
cant generate 

### ISSUE THREAD

**Issue by jesse234** [Technowlogy-Pushpender/KratosKnife#9]
pretty much looks like a good tool but does not generate exe , i am currently having a traceback in Generator.py

**Comment by FrenchCisco** [comment]
Thank you for the feedback.
Can you give me more information about the error in question?

**Comment by jesse234** [comment]
thanks for your  response , i get these traceback on kali linux  when i try to run generator.py 

/bin/sh: 1: where: not found
Traceback (most recent call last):
  File "/root/Desktop/KratosKnife/Botnet-Generator/Generator.py", line 160, in <module>
    PYTHON_PYINSTALLER_PATH = get_python_pyinstaller_path()
  File "/root/Desktop/KratosKnife/Botnet-Generator/Generator.py", line 35, in get_python_pyinstaller_path
    python_path = subprocess.check_output("where python", shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'where python' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/KratosKnife/Botnet-Generator/Generator.py", line 248, in <module>
    del_junk_file(file_name)
NameError: name 'file_name' is not defined

this was my command : python3 Generator.py -s http://xxxxxxxxxxxxxxx.com/panel -o book --icon icon/book.ico

on the output i have even tried .exe on book.exe i still get thesame error


And kratosknife runs currently on python3

**Comment by PushpenderIndia** [comment]
Create payload from windows machine, as this botnet is for windows only

**Comment by jesse234** [comment]
cool bro and thanks for the response, please i have an issue when running generator.py on windows i get this error 'C:/Users/user' is not recognized as an internal or external command,
operable program or batch file.
pls could you suggest to me on how to get this error cleared ? tnks bro

**Comment by jesse234** [comment]
cool bro and thanks for the response, please i have an issue when running generator.py on windows i get this error 'C:/Users/user' is not recognized as an internal or external command,
operable program or batch file.
pls could you suggest to me on how to get this error cleared ? tnks bro

**Comment by jesse234** [comment]
sorry bro your botnet dont work alot of errors , and edit your readme to add pyinstaller path on generator.py but still much errors . thanks anyways not bad of an effort
